// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgGWvVAugBnslgYskJeuTCaYu47PZEOPs',
    appId: '1:197055685231:web:95baebfc093d5e4eb6639a',
    messagingSenderId: '197055685231',
    projectId: 'prakflutterfirebase-ce41d',
    authDomain: 'prakflutterfirebase-ce41d.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-ce41d.appspot.com',
    measurementId: 'G-YNPB151J58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7f_rDthXnP0UIsfHTFkktfhqHTEF25EM',
    appId: '1:197055685231:android:3252e8f133ab53eab6639a',
    messagingSenderId: '197055685231',
    projectId: 'prakflutterfirebase-ce41d',
    storageBucket: 'prakflutterfirebase-ce41d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBzEZbA5vLDhIYaMK2LTx85rJKoNaqAPw',
    appId: '1:197055685231:ios:c2b594ec039eeaeeb6639a',
    messagingSenderId: '197055685231',
    projectId: 'prakflutterfirebase-ce41d',
    storageBucket: 'prakflutterfirebase-ce41d.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBzEZbA5vLDhIYaMK2LTx85rJKoNaqAPw',
    appId: '1:197055685231:ios:c2b594ec039eeaeeb6639a',
    messagingSenderId: '197055685231',
    projectId: 'prakflutterfirebase-ce41d',
    storageBucket: 'prakflutterfirebase-ce41d.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgGWvVAugBnslgYskJeuTCaYu47PZEOPs',
    appId: '1:197055685231:web:5c0ff941d8ce9300b6639a',
    messagingSenderId: '197055685231',
    projectId: 'prakflutterfirebase-ce41d',
    authDomain: 'prakflutterfirebase-ce41d.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-ce41d.appspot.com',
    measurementId: 'G-145HT1W3Y9',
  );
}
